# Generated by Django 5.1 on 2024-08-15 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('quantity', models.PositiveIntegerField()),
                ('measurement_unit', models.CharField(choices=[('kg', 'Kilograms'), ('ml', 'Milliliters'), ('pcs', 'Pieces')], default='kg', max_length=3)),
            ],
        ),
    ]
