# Generated by Django 5.1 on 2024-08-15 19:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0002_initial'),
        ('suppliers', '0002_remove_supplier_supplied_ingredients_supplier_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='supplier',
        ),
        migrations.CreateModel(
            name='SupplierIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_per_unit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_ingredients', to='ingredients.ingredient')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_ingredients', to='suppliers.supplier')),
            ],
            options={
                'unique_together': {('supplier', 'ingredient')},
            },
        ),
    ]
