# Generated by Django 5.1 on 2024-08-15 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ingredients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('contact_info', models.TextField()),
                ('supplied_ingredients', models.ManyToManyField(blank=True, related_name='supplied_by', to='ingredients.ingredient')),
            ],
        ),
    ]
