# Generated by Django 5.1 on 2024-08-15 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplier',
            name='supplied_ingredients',
        ),
        migrations.AddField(
            model_name='supplier',
            name='email',
            field=models.EmailField(default='default@example.com', max_length=255, unique=True),
        ),
    ]
