# Generated by Django 5.1 on 2024-08-15 18:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dishes', '0001_initial'),
        ('ingredients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dishingredient',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ingredients.ingredient'),
        ),
        migrations.AddField(
            model_name='dish',
            name='ingredients',
            field=models.ManyToManyField(through='dishes.DishIngredient', to='ingredients.ingredient'),
        ),
        migrations.AlterUniqueTogether(
            name='dishingredient',
            unique_together={('dish', 'ingredient')},
        ),
    ]
