# Generated by Django 5.1 on 2024-08-17 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_remove_order_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completefrom django.contrib.auth import get_user_modeld', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=55),
        ),
    ]
